### ISSUE TITLE
Test Backend Changes

### ISSUE THREAD

**Issue by LouisMuhr** [DieNullpointer/fit#34]

**Comment by BastiMagOrangen** [comment]
Deine Delete Methode wird nicht funktionieren, so wie du sie gemacht hast. Da du einen Foreign Key hast der mit gelöscht werden muss!
Hier ein Beispiel vom Löschen der Firma. Da werden zuerst die Contact Partner gelöscht:
`public async Task<bool> DeleteCompany(Guid guid)
        {
            var company = await _db.Companies.Include(c=>c.ContactPartners).FirstAsync(a => a.Guid == guid);
            if (company is null)
                throw new ServiceException("Firma gibt es nicht");

            _db.ContactPartners.RemoveRange(company.ContactPartners.ToList());
            try
            {
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateException e) { throw new ServiceException(e.InnerException?.Message ?? e.Message, e); }
            _db.Companies.Remove(company);
            try
            {
                await _db.SaveChangesAsync();
            }
            catch (DbUpdateException e) { throw new ServiceException(e.InnerException?.Message ?? e.Message, e); }
            return true;
        }`
