### ISSUE TITLE
Change ContactPartner

### ISSUE THREAD

**Issue by BastiMagOrangen** [DieNullpointer/fit#51]
- [x] Add ContactPartner Controller
- [x] Add Change Method
- [x] Test Change Method

**Comment by BastiMagOrangen** [comment]
Mir sind ein paar Dinge aufgefallen:

`C#
public ChangeCmd(string id,string title, string firstname, string lastname, string email, string telNr, string? mobilNr, string function)
        [HttpPost]
        public async Task<IActionResult> ChangeContact([FromBody]ChangeCmd changeContact)
        {
            var contact = await _db.Contacts.FindAsync(changeContact.Id);
            if (contact == null)
                    return NotFound("Kontakt nicht gefunden");   

            contact.Title = changeContact.Title;
            contact.FirstName = changeContact.FirstName;
            contact.LastName = changeContact.LastName;
            contact.Email = changeContact.Email;
            contact.TelNr = changeContact.TelNr;
            contact.MobilNr = changeContact.MobilNr;
            contact.Function = changeContact.Function;

            await _db.SaveChangesAsync();
            return Ok("Kontakt erfolgreich geändert");
            }
`

Mach bei ChangeCmd lieber

`C#
public ChangeCmd(Guid guid,string title, string firstname, string lastname, string email, string telNr, string function, string? mobilNr = null)
` 
Mit der Guid ist es sicherer Daten zu suchen und zu ändern und mobilNr am Ende, da falls diese nicht mitgegeben wird standardmäßig auf null gesetzt wird. Da das Feld nicht notwendig ist.

Danach habe ich noch paar Verbesserungen:

`C#
var contact = await _db.Contacts.FindAsync(a => a.Guid == changeContact.guid);
if (contact is null)


try
{
     await _db.SaveChangesAsync();
}
catch (DbUpdateException e) { throw new ServiceException(e.InnerException?.Message ?? e.Message, e); }
return Ok(contact.Guid);
`

**Comment by BastiMagOrangen** [comment]
Genau

**Comment by Machsiim** [comment]
🫶
